# Generated by Django 4.2.2 on 2023-06-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='images/avatar.jpg', upload_to='profile_images'),
        ),
    ]
