# Generated by Django 4.2.2 on 2023-06-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_images'),
        ),
    ]
