# Generated by Django 4.2.2 on 2023-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
