# Generated by Django 4.2.2 on 2023-06-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_online_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='online_status',
            new_name='is_online',
        ),
    ]
