# Generated by Django 4.2.2 on 2023-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_online_status_account_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
    ]
