# Generated by Django 4.2.2 on 2023-07-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_receiver_alter_message_sent_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
